name: "Code Analysis"

on:
  push:
    branches: [ "**" ]

jobs:
  codeql:
    name: Analyze (${{ matrix.language }})
    runs-on: ${{ (matrix.language == 'swift' && 'macos-latest') || 'ubuntu-latest' }}
    timeout-minutes: ${{ (matrix.language == 'swift' && 120) || 360 }}
    permissions:
      security-events: write
      packages: read

    strategy:
      fail-fast: false
      matrix:
        include:
        - language: javascript-typescript
          build-mode: none

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Run CodeQL
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        build-mode: ${{ matrix.build-mode }}
        config-file: GitHubSecurityLab/CodeQL-Community-Packs/configs/default.yml@main

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:${{matrix.language}}"

    # Run DevSkim
    - name: Run DevSkim scanner
      uses: microsoft/DevSkim-Action@v1.0.14

    - name: Upload DevSkim scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: devskim-results.sarif

    # Trufflehog
    - name: TruffleHog OSS
      uses: trufflesecurity/trufflehog@v3.81.8
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --results=verified
